### ISSUE TITLE
Video Processing Time

### ISSUE THREAD

**Issue by Abdullah-Rekd** [dev-labs-bg/swift-video-generator#66] opened 2020-01-22 12:23 UTC
Hi , I am using your pod for Gif to Video .. 
Working : 
Gif to images array 
images array passed to VideoGenerator.current 

Issue I am facing that it took a lot of time for generating video. 
for example I have array of images count 42 , so it takes approx 30-40 seconds for whole process where as I want this process in more less time. Can you please suggest me how to do this ??

**Comment by tgeorgieva** [comment] 2020-01-22 12:35
@Abdullah-Rekd Hello. I'm sorry that you find this to be a long time. The processing time is determined by the algorithm and the device's capabilities. Let's not forget these are phones, not computers. 

I've cleaned up the algorithm as much as I can. I don't thing 30 seconds is a long time, especially considering that it's using gifs. 

I can't suggest anything in terms of improving time because I think it's normal for a larger number of input resources to take a longer processing time.

I'm using Apple's methods for image and audio processing so I don't think there's anything more to be done that will significantly improve the time. I don't think you'll be able to shed more than a few seconds but feel free to fork the project and try to improve the algorithm.

I'm closing the issue because this is not a bug. If you find ways to improve this feel free to send a Merge request and I will reflect the changes here.

**Closed as completed** 2020-01-22 12:38 UTC

**Comment by Abdullah-Rekd** [comment] 2020-01-23 04:39
Great thanks.

**Comment by Abdullah-Rekd** [comment] 2020-01-23 05:38
The processing time is determined by the algorithm and the device's capabilities. Let's not forget these are phones, not computers.

^^ I've tested on simulator of
MacBook Pro 2018 
2.2 GHz 6-Core Intel Core i7
16 GB 2400 MHz DDR4
Intel UHD Graphics 630 1536 MB

Do you think this Mac should take much time for processing ?
